proc gsSnapVertex(string $vtxSrc[], string $vtxDst[], float $eps){
	string $closestVert ;
	for ($i=0;$i<size($vtxDst);$i++)
	{
		float $shortestDistance = 1000000;
		
		//select $vtxDst[$i];
		float $vPos[] = `xform -q -ws -t $vtxDst[$i]`;
					
		for ($j=0;$j<size($vtxSrc);$j++)
		{
			float $testVert[] = `xform -q -ws -t $vtxSrc[$j]`;
			float $testLength = ((($testVert[0] - $vPos[0])*($testVert[0] - $vPos[0])) + (($testVert[1] - $vPos[1])*($testVert[1] - $vPos[1])) + (($testVert[2] - $vPos[2])*($testVert[2] - $vPos[2])));
			
			if ($testLength < $shortestDistance)
			{
				$closestVert = $vtxSrc[$j];
				$shortestDistance = $testLength;
			}
		}
		if ($shortestDistance < $eps){
			float $posSrc[] = `xform -q -ws -t $closestVert`;
			xform -ws -t $posSrc[0] $posSrc[1] $posSrc[2] $vtxDst[$i];
		}
	}
}
global proc gsSnapToTheOtherObject(){
	float $eps = `textField -q -text lnThreshole`;
	string $curName = `button -q -l btPick`;
	string $sel[] = `ls -sl -l -fl`; select -cl;
	
	string $typeObj = `nodeType $sel[size($sel)-1]`; 
	if ($typeObj == "transform"){
        string $vtSel[], $vtSrc[];
        for ($i=0;$i<(size($sel) - 1);$i++)
        {
            $vtSel[$i] = $sel[$i];
        }
        select $sel[size($sel)-1];
        ConvertSelectionToVertices;
        $vtSrc = `ls -sl -fl -l`;
        gsSnapVertex($vtSrc, $vtSel, $eps);
        select -r $vtSel;
    }
    else if ($typeObj != "transform"){
        string $vtSel[], $vtSrc[];
        for ($i=0;$i<(size($sel));$i++)
        {
            $vtSel[$i] = $sel[$i];
        }
        string $sourceObj = `button -q -l btPick`;
        select $sourceObj;
        ConvertSelectionToVertices;
        $vtSrc = `ls -sl -fl -l`;
        gsSnapVertex($vtSrc, $vtSel, $eps);
        select -r $vtSel;
    }
}
global proc gsSnapToObjectItself(){
	string $vtSel[] = `ls -l -fl -sl`;
	string $objSel[] = `ls -l -hilite` ;
	select -cl;
	select $objSel[0] ;
	ConvertSelectionToVertices ;
	string $vtSrc[] = `ls -l -fl -sl`;
	select -cl ;
	$vtSrc = stringArrayRemove($vtSel, $vtSrc);
	float $eps = `textField -q -text lnThreshole` ;
	gsSnapVertex($vtSrc, $vtSel, $eps);
}

global proc selectSource(){
    string $selSource[] = `ls -sl`;
    if (size($selSource) == 0) {
        warning "chua chon object";
    }
    else{
        //print ($selSource[0]);
        button -e -l $selSource[0] btPick;
    }
}

global proc gsSnapVertexTools(){
	global string $GS_SRIPT_SRV_DIR ;
	setTRSPreserveUVs true;
	if (`window -ex "gsSnapVertexWin"`)
        deleteUI "gsSnapVertexWin" ;
	string $snapVertexWin = `window  -rtf 1 -wh 305 103 -t "GS Snap Vertex Tools" gsSnapVertexWin` ;
	columnLayout -adj true topCol;
		frameLayout -collapsable 1 -collapse 0 -l "" -mw 10;
			columnLayout -adj true sampleCol;
 		        separator -style "none" -h 10;
				rowLayout -numberOfColumns 2 -cw2 150 150 sampleRow;
					text -label "Threshole:"  -align "right";
					textField -text "100" -w 100 lnThreshole; 
				setParent ..;
				separator -style "none" -h 10;
				rowLayout -numberOfColumns 2 -cw2 120 120 sampleRow1;
					button -label "Snap to Object itself" -ann "Snap selected vetices to nearest vertex on the same Object" -command gsSnapToObjectItself btSnapToObjectItself;
					button -label "Snap to the other Object" -ann "Snap selected vetices to nearest vertex the next Selected Object" -command gsSnapToTheOtherObject btSnapToTheOtherObject;
				setParent ..;
				separator -style "none" -h 10;
				button -label "Pick Source" -ann "Pick Some Object In Scene" -command selectSource btPick;
 		    setParent ..; // link to FrameLayout
 		setParent ..;     // link to ColumnLayout "sampleCol"
	showWindow $snapVertexWin ;
}