// =====================================================================
//  DM Normal Tools
//  Version: 1.13
//  Author: Dmytro Lystopad
//  Description: A tool for aligning vertex normals in Maya.
//               Includes face-weighted and average normal algorithms.
//               The "Keep Hard Edges" option preserves shading on hard edges, keeping them visually sharp.
//               Normal values can be copied and pasted via the UI.
//               Supports aligning normals on single and multiple objects simultaneously, or selected components (vertices, faces, or vertex faces).
// =====================================================================

global proc dmnt_showUI(int $showNormal, float $normalSize)
{
    if (`window -exists DMNTwin`)
    {
        deleteUI DMNTwin;
        windowPref -r DMNTwin;
    }
    if (`window -exists DMNTHelpWin`)
    {
        deleteUI DMNTHelpWin;
        windowPref -r DMNTHelpWin;
    }

    float $mayaVersion = getApplicationVersionAsFloat();

    window -t "GS Normal Tools" -s 0 -w 270 -rtf 1 DMNTwin;

    columnLayout -adj 1 -cat "both" 0 -cal "center";
        frameLayout -l "Align Normals" -bgs 1;
            rowLayout -nc 2 -rat 1 "both" 2;
                columnLayout -adj 1 -cat "both" 0;
                    radioButtonGrp -w 130 -nrb 2 -la2 "Face Weighted" "Average" -an1 "For each vertex, the script takes the full normal of the face that has the largest area among all faces that use that vertex." -an2 "For each vertex, the script assigns an average normal calculated based on the normals of neighboring faces." -select 1 -vr alignMethodRBG;
                    checkBox -w 130 -l "Keep Hard Edges" -ann "Preserve the shading for hard edges so they still appear sharp." keepHardEdgesCB;
                setParent ..;
                rowLayout -nc 1 -adj 1;
                    button -w 130 -l "Align Normals" -c "dmnt_alignNormalsFromUI" -ann "Select an object or its component to align vertex normals" -h 60 alignNormalsBTN;
                setParent  ..;
            setParent  ..;
        setParent  ..;

        frameLayout -l "Adjust Normals" -bgs 1;
            columnLayout -adj 1 -cat "both" 0 -cal "center";
                rowLayout -nc 3 ;
                    if ($mayaVersion > 2018)
                        floatFieldGrp -nf 3 -value1 0 -value2 0 -value3 0 -pre 6 -cw3 60 60 60 -ekf 1 -ann "X, Y and Z values of the normal." normalFFG;
                    else floatFieldGrp -nf 3 -value1 0 -value2 0 -value3 0 -pre 6 -cw3 60 60 60 -ann "X, Y and Z values of the normal." normalFFG;
                        button -w 35 -l "Get" -c "dmnt_copyNormalFromUI()" -ann "Get normal from the selected component." getNormalBTN;
                        button -w 35 -l "Set" -c "dmnt_pasteNormalFromUI()" -ann "Set normal to the selected component." setNormalBTN;
                    setParent ..;
                    rowLayout -nc 2;
                        button -w 131 -l "Average From Edge" -c "dmnt_alignNormalsOnEdgeFormUI" -ann "Apply average normal from connected faces to the vertices of the selected edge." averageFromEdgeBTN;
                        button -w 131 -l "Vertex Normal Edit Tool" -c "dmnt_switchToNormalEditToolFromUI" -ann "This tool allows you to manually adjust the vertex normals of the selected components by rotating the manipulator." normalEditToolBTN;
                    setParent ..;
                    rowLayout -nc 2;
                        button -w 131 -l "Unlock Normals" -c "dmnt_unlockNormals()" -ann "Unlocks normals and restores soft and hard edges. Can be applied to a single object, multiple objects, or vertices." unlockNormalBTN;
                        button -w 131 -l "Lock Normals" -c "dmnt_lockNormals()" -ann "Locks vertex normals with their current values. Can be applied to a single object, multiple objects, or vertices." lockNormalBTN;
                    setParent ..;
                setParent ..;
            setParent ..;
        setParent  ..;

        frameLayout -l "Selection" -bgs 1;
            columnLayout -adj 1 -cat "both" 0;
                rowLayout -nc 2;
                    button -w 131 -l "Select Hard Edges" -c "dmnt_selectEdgesFromUI(1)" -ann "Gets hard edges from the selected objects or components. ALT + click to use alternative method (slower)" selectHardEdgesBTN;
                    button -w 131 -l "Select Soft Edges" -c "dmnt_selectEdgesFromUI(0)" -ann "Gets soft edges from the selected objects or components. ALT + click to use alternative method (slower)" selectSoftEdgesBTN;
                setParent ..;
                columnLayout -adj 1 -cat "both" 0;
                    button -l "Convert to Vertex Faces" -c "dmnt_selectVertexFacesFromUI" -ann "Converts selection to Vertex Face components." selectVertexFacesBTN;
                setParent ..;
            setParent ..;
        setParent  ..;  

        frameLayout -l "Display options" -bgs 1;
                columnLayout -adj 1 -cat "both" 0;
                    checkBox -l "Show Vertex Normals" -ann "Enables displaying vertex normals" -cc "dmnt_onSettingsChanged" -v $showNormal showNormalsCB;
                    floatSliderGrp -l "Normal Size:" -ann "Specifies the length of the normal to be displayed." -cal 1 "left" -field 1 -min 0.1 -max 25 -fieldMinValue 0.1 -fieldMaxValue 500 -value $normalSize -fs 0.1 -cw3 70 70 50 -cc "dmnt_onSettingsChanged" -dc "dmnt_onSettingsChanged" normalSizeFSG;
                setParent  ..;
        setParent  ..;

        columnLayout -adj 2 -cat "both" 0;
        separator;
            rowLayout -nc 2 -adj 1 -rat 1 "both" 0;
                text -l "GS Normal Tools v1.13" -al "center" -en 0;
                iconTextButton -w 15 -h 15  -st "iconOnly" -i "help.png" -ann "Open Help" -c "dmnt_showHelp()" -hlc 1 1 1;
            setParent ..;
        separator;
        setParent ..;

    setParent  ..;

    dimWhen -false SomethingSelected alignNormalsBTN;
    dimWhen -false SomethingSelected getNormalBTN;
    dimWhen -false SomethingSelected setNormalBTN;
    dimWhen -false SomethingSelected averageFromEdgeBTN;
    dimWhen -false SomethingSelected selectHardEdgesBTN;
    dimWhen -false SomethingSelected selectSoftEdgesBTN;
    dimWhen -false SomethingSelected selectVertexFacesBTN;
    dimWhen -false SomethingSelected unlockNormalBTN;
    dimWhen -false SomethingSelected lockNormalBTN;
    dimWhen -false SomethingSelected normalEditToolBTN;

    showWindow DMNTwin;
}

global proc dmnt_showHelp()
{
    if (`window -exists DMNTHelpWin`)
    {
        deleteUI DMNTHelpWin;
        windowPref -r DMNTHelpWin;
    }

    window -t "DM Normal Tools - Help" -s 0  -rtf 1 DMNTHelpWin;

    columnLayout -adj 1 -cat "both" 0 -cal "center";
        separator -style "in" -w 10 -h 10;
            text -l "GS Normal Tools v1.13" -al "center" -fn "boldLabelFont";
        separator -style "out" -w 10 -h 10;
    setParent  ..;

    columnLayout -adj 1 -cat "both" 15 -cal "left";
        text -l "\nFeatures overview" -al "center" -fn "boldLabelFont";

        text -l "\nAlign Normals:" -fn "boldLabelFont";
        text -l ("Aligns normals depending on the chosen algorithm:" +
                "\nFace Weighted - For each vertex, the script takes the full normal of the face that has the largest area among all faces that are connected to that vertex." +
                "\nAverage - For each vertex, the script assigns an average normal calculated based on the normals of neighboring faces." +
                "\nKeep Hard Edges - This option preserves shading on hard edges, keeping them visually sharp." +

                "\n\nAligning normals can be applied to a single object, multiple objects simultaneously, or selected components (vertices, faces, or vertex faces).");

        text -l "\nAdjust Normals:" -fn "boldLabelFont";
        text -l ("Get - Gets the normal from the selected component. If multiple components are selected, it gets the average normal from the selected components." +
                "\nSet - Applies normal from normal input fields to selected components." +
                "\nAverage From Edge - Applies average normal from connected faces to the vertices of the selected edge." +
                "\nVertex Normal Edit Tool - This tool allows you to manually adjust the vertex normals of the selected components by rotating the manipulator. Select a vertex or a vertex face to edit the normal vector." +
                "\nUnlock Normals - Unlocks normals and restores soft and hard edges. Can be applied to a single object, multiple objects, or vertices." +
                "\nLock Normals - Locks vertex normals with their current values. Can be applied to a single object, multiple objects, or vertices.");

        text -l "\nSelection:" -fn "boldLabelFont";
        text -l ("Select Hard Edges - Gets hard edges from the selected objects or components." +
                "\nSelect Soft Edges - Gets soft edges from the selected objects or components." +
                "\nConvert to Vertex Faces - Converts selection to Vertex Face components." +

                "\n\nSelecting Hard and Soft edges supports an alternative search method that depends on vertex normals." +
                "\nThis method is slower but works on meshes with locked normals when Maya marks edges as hard, even if they appear smooth." +
                "\nNon-manifold edges are considered as hard. ALT + LMB on the button to use this method.");

        text -l "\nDisplay options:" -fn "boldLabelFont";
        text -l ("Show Vertex Normals - Enables displaying vertex normals" +
                "\nNormal Size - Specifies the length of the normal to be displayed.");

        text -l "\nContact" -al "center" -fn "boldLabelFont";
        text -l "For bug reports, feature requests, or other questions, contact:";
        rowLayout -nc 2;
            text -l "E-mail:";
            text -l "<a href=\"mailto:lystopad.support@pm.me\">lystopad.support@pm.me</a>" -hl 1;
        setParent  ..;
        rowLayout -nc 2;
            text -l "Gumroad:";
            text -l "<a href=\"https://lystopad.gumroad.com/\">lystopad.gumroad.com</a>" -hl 1;
        setParent  ..;

    setParent  ..;

    columnLayout -adj 1 -cat "both" 0 -cal "center";
        separator -style "in" -w 10 -h 10;
            text -l "Dmytro Lystopad" -al "center" -fn "obliqueLabelFont";
        separator -style "out" -w 10 -h 10;
    setParent  ..;

    showWindow DMNTHelpWin;
}
global proc dmnt_copyNormalFromUI()
{
    vector $normal = dmnt_getNormalFromComponents(ls("-sl", "-fl", "-l"));
    floatFieldGrp -e -v1 ($normal.x) -v2 ($normal.y) -v3 ($normal.z) normalFFG;
}

global proc dmnt_pasteNormalFromUI()
{   
    string $selection[] = ls( "-sl", "-fl", "-l");
    string $selectedVerticies[] = filterExpand("-sm", 31, $selection);
    string $softEdges[] = dmnt_getEdges($selectedVerticies, 0);
    vector $normal = `floatFieldGrp -q -v normalFFG`;

    polyNormalPerVertex -xyz ($normal.x) ($normal.y) ($normal.z) (ls("-fl", "-l", polyListComponentConversion("-tvf", $selection)));

    if (size($selectedVerticies) > 0 && size($softEdges) > 0)
    {
        polySoftEdge -a 360 $softEdges;
        select -r $selection;
    }
}

global proc dmnt_switchToNormalEditToolFromUI()
{
    setToolTo polyVertexNormalEdit;
}

global proc dmnt_onSettingsChanged()
{
    int $showNormal = `checkBox -q -v showNormalsCB`;       
    float $normalSize = `floatSliderGrp -q -v normalSizeFSG`;
    
    polyOptions -dn $showNormal -pt -sn $normalSize -gl;
}

global proc dmnt_selectEdgesFromUI(int $hardEdges)
{
    string $edges[];

    $edges = dmnt_getEdges(ls("-sl", "-fl", "-l"), $hardEdges);

    select -r $edges;
}

global proc dmnt_selectVertexFacesFromUI()
{
    select("-r", polyListComponentConversion("-tvf"));
}

global proc dmnt_alignNormalsOnEdgeFormUI()
{
    string $edges[] = ls( "-sl", "-fl", "-l", filterExpand("-sm", 32));

    if (size($edges) == 0)
    {
        print ("No edges selected. Select at least one edge to perform Average From Edge.\n");
        return;
    }

    dmnt_setAverageNormalFromEdges($edges);
}

global proc dmnt_alignNormalsFromUI()
{
    int $method = `radioButtonGrp -q -select alignMethodRBG`;
    int $keepHardEdges = `checkBox -q -value keepHardEdgesCB`;
    dmnt_alignNormals($method, $keepHardEdges);
}

global proc dmnt_alignNormals(int $method, int $keepHardEdges)
{
    string $selection[] = ls("-sl", "-l", "-fl");
    string $selectedShapes[] = ls("-dag", "-lf", "-l", "-o", $selection);

    if (size($selection) == 0)
        error "Please select a mesh or components.";

    for ($shape in $selectedShapes)
        if (`objectType $shape` != "mesh")
            error "Selection is not a mesh.";

    string $vertexFaces[] = ls( "-l", "-fl", filterExpand("-sm", 70, $selection));

    if (size($vertexFaces) > 0)
    {
        string $selectedObjects[] = ls("-sl", "-l", "-o", $vertexFaces);
        for ($obj in $selectedObjects)
        {
            string $objSelection[] = ls("-sl", "-l", "-fl", $obj);
            string $targetVertexFaces[] = ls( "-l", "-fl", filterExpand("-sm", 70, $objSelection));

            dmnt_alignVertexFaceNormals($targetVertexFaces, $method, $keepHardEdges);
        }

        string $tmpSelection[] = stringArrayRemove($vertexFaces, $selection);

        if (size($tmpSelection) > 0)
        {
            string $vertices[] = ls( "-fl", "-l", polyListComponentConversion("-tv", $tmpSelection));
            dmnt_alignVertexNormals($vertices, $method, $keepHardEdges);
        }
    }
    else 
    {
        string $vertices[] = ls( "-fl", "-l", polyListComponentConversion("-tv"));
        dmnt_alignVertexNormals($vertices, $method, $keepHardEdges);
    }

    print("Vertex normals have been aligned\n");
    select -r $selection;
}

global proc dmnt_alignVertexFaceNormals(string $vertexFaces[], int $method, int $keepHardEdges)
{
    string $allVertexFaces[] = $vertexFaces;

    while (size($vertexFaces) > 0)
    {
        string $vertex[] = ls("-l", "-fl", polyListComponentConversion("-tv", $vertexFaces[0]));
        string $adjacentVertexFaces[] =  dmnt_stringArrayIntersection($allVertexFaces, ls("-l", "-fl", polyListComponentConversion("-tvf", $vertex)));
        string $targetVertexFaces[];
        string $connectedFaces[];
        string $softEdges[];
        vector $normal;

        if ($keepHardEdges && size(dmnt_getEdges($vertex, 1)) > 0)
            $targetVertexFaces = dmnt_getNeighborVertexFaces($vertexFaces[0], $adjacentVertexFaces);
        else
            $targetVertexFaces = $adjacentVertexFaces;

        $connectedFaces = ls( "-fl", "-l", polyListComponentConversion("-tf", $targetVertexFaces));
        $softEdges = dmnt_getEdges(polyListComponentConversion("-te", "-in", $connectedFaces), 0);
        $normal = ($method == 1 ? dmnt_getNormalFromFace(dmnt_getLargestFace($connectedFaces)) : dmnt_getNormalFromFaces($connectedFaces));

        polyNormalPerVertex -xyz ($normal.x) ($normal.y) ($normal.z) $targetVertexFaces;

        if (size($softEdges) > 0)
            polySoftEdge -a 360 $softEdges;

        $vertexFaces = stringArrayRemove($targetVertexFaces, $vertexFaces);
    }
    
}

global proc string[] dmnt_getNeighborVertexFaces(string $vertexFace, string $vertexFaces[])
{
    string $visited[] = {};
    string $queue[] = {$vertexFace};
    
    while (size($queue) > 0)
    {
        string $currentVertexFace = $queue[0];
        $queue = stringArrayRemove({$currentVertexFace}, $queue);
        
        if (stringArrayContains($currentVertexFace, $visited) == 0) 
        {
            $visited[size($visited)] = $currentVertexFace;
            string $softEdges[] = dmnt_getEdges({$currentVertexFace}, 0);
            string $adjacentVertexFaces[] = ls("-l", "-fl", polyListComponentConversion("-tvf", $softEdges));
            
            for ($vertexFace in $adjacentVertexFaces) {
                if (stringArrayContains($vertexFace, $vertexFaces) && !stringArrayContains($vertexFace, $visited)) {
                    $queue[size($queue)] = $vertexFace;
                }
            }
        }
    }
    return $visited;
}

global proc dmnt_alignVertexNormals(string $vertices[], int $method, int $keepHardEdges)
{
    for ($vertex in $vertices)
    {
        string $connectedFaces[];
        vector $normal;

        if ($keepHardEdges && size(dmnt_getEdges({$vertex}, 1)) > 0)
        {
            string $vertexFaces[] = ls("-fl", "-l", polyListComponentConversion("-tvf", $vertex));
            string $allVertexFaces[] = $vertexFaces;
            string $softEdges[];
            string $adjacentSoftEdges[];

            while (size($vertexFaces) > 0)
            {
                $targetVertexFaces = dmnt_getNeighborVertexFaces($vertexFaces[0], $allVertexFaces);
                $connectedFaces = ls( "-fl", "-l", polyListComponentConversion("-tf", $targetVertexFaces));
                $adjacentSoftEdges = dmnt_getEdges(polyListComponentConversion("-te", "-in", $connectedFaces), 0);
                $normal = ($method == 1 ? dmnt_getNormalFromFace(dmnt_getLargestFace($connectedFaces)) : dmnt_getNormalFromFaces($connectedFaces));

                polyNormalPerVertex -xyz ($normal.x) ($normal.y) ($normal.z) $targetVertexFaces;

                if (size($adjacentSoftEdges) > 0)
                    $softEdges = stringArrayCatenate($softEdges, $adjacentSoftEdges);

                $vertexFaces = stringArrayRemove($targetVertexFaces, $vertexFaces);
            }
            if (size($softEdges) > 0)
                polySoftEdge -a 360 $softEdges;
        }
        else
        {
            $connectedFaces = ls( "-fl", "-l", polyListComponentConversion("-tf", $vertex));
            $normal = ($method == 1 ? dmnt_getNormalFromFace(dmnt_getLargestFace($connectedFaces)) : dmnt_getNormalFromFaces($connectedFaces));
            polyNormalPerVertex -xyz ($normal.x) ($normal.y) ($normal.z) $vertex;
        }
    }
}

global proc dmnt_setAverageNormalFromEdges(string $edges[])
{
    for ($edge in $edges)
    {
        string $connectedFaces[] = ls( "-fl", "-l", (polyListComponentConversion("-fe", "-tf", $edge)));
        vector $normal = dmnt_getNormalFromFaces($connectedFaces);
        string $vertices[] = ls( "-fl", "-l", (polyListComponentConversion("-fe", "-tv", $edge)));

        for ($vertex in $vertices)
            polyNormalPerVertex -xyz ($normal.x) ($normal.y) ($normal.z) $vertex;
    }
}

global proc vector dmnt_getNormalFromFace(string $face)
{
    vector $normal;
    float $nx, $ny, $nz;
    string $polyInfo[] = `polyInfo -fn $face`;
    string $tokens[];
    
    tokenize $polyInfo[0] $tokens;
    $nx = $tokens[2];
    $ny = $tokens[3];
    $nz = $tokens[4];
    $normal = unit(<<$nx, $ny, $nz>>);

    return $normal;
}

global proc string dmnt_getLargestFace(string $faceList[])
{
    string $largestFace;
    float $largestArea = 0;

    for($face in $faceList)
    {
        float $area[] = `polyEvaluate -wfa $face`;

        if($area[0] > $largestArea)
        {
            $largestArea = $area[0];
            $largestFace = $face;
        }
    }
    return $largestFace;
}

global proc string[] dmnt_getEdges(string $selection[], int $getHardEdges)
{
    string $result[];
    string $allEdges[] = ls("-fl", "-l", polyListComponentConversion("-te", "-vfa", $selection));

    int $modifiers = getModifiers();

    if ($modifiers / 8 % 2) // Alt pressed
    {
        for ($e = 0; $e < size($allEdges); $e++)
            if ($getHardEdges == dmnt_isEdgeHard($allEdges[$e]))
                $result[size($result)] = $allEdges[$e];
    }
    else
    {
        for ($e = 0; $e < size($allEdges); $e++)
        {
            string $edgeInfo[] = `polyInfo -ev $allEdges[$e]`;

            if ($getHardEdges == gmatch($edgeInfo[0],"*Hard*"))
                $result[size($result)] = $allEdges[$e];
        }
    }

    return $result;
}

global proc vector dmnt_getNormalFromVertices(string $vertices[])
{
    $vertices = ls("-fl", "-l", filterExpand("-sm", 31, $vertices));
    vector $normal = <<0, 0, 0>>;
    float $normals[] = `polyNormalPerVertex -q -xyz $vertices`;
    
    for ($i = 0; $i < size($normals); $i += 3)
        $normal += << $normals[$i], $normals[$i + 1], $normals[$i + 2] >>;
    
    return unit($normal/size($normals)/3);
}

global proc vector dmnt_getNormalFromVertexFaces(string $vertexFaces[])
{
    $vertexFaces = ls("-fl", "-l", filterExpand("-sm", 70, $vertexFaces));
    vector $normal = <<0, 0, 0>>;
        
    if (size($vertexFaces) > 1)
    {
        for ($vertexFace in $vertexFaces)
            $normal += `polyNormalPerVertex -q -xyz $vertexFace`;
            
        $normal = unit($normal/size($vertexFaces));
    }
    else $normal = `polyNormalPerVertex -q -xyz $vertexFaces[0]`;
    
    return $normal;
}

global proc vector dmnt_getNormalFromFaces(string $faces[])
{
    $faces = ls("-fl", "-l", filterExpand("-sm", 34, $faces));
    vector $normal = <<0, 0, 0>>;
            
    for ($face in $faces)    
        $normal += dmnt_getNormalFromFace($face);

    return (size($faces) > 0 ? unit ($normal / size($faces)) : $normal);
}

global proc vector dmnt_getNormalFromComponents(string $components[])
{   
    if (size(filterExpand("-sm", 31, $components)) > 0) //Vertex
        return dmnt_getNormalFromVertices($components);
    else if (size(filterExpand("-sm", 34, $components)) > 0) //Face
        return dmnt_getNormalFromFaces($components);
    else if (size(filterExpand("-sm", 70, $components)) > 0) //Vertex Face
        return dmnt_getNormalFromVertexFaces($components);
    else if (size(filterExpand("-sm", 32, $components)) > 0) //Edge
    {
        string $faces[] = ls("-fl", "-l", polyListComponentConversion("-tf", filterExpand("-sm", 32, $components)));
        return dmnt_getNormalFromFaces($faces);
    }
    
    else return <<0, 0, 0>>;
}

global proc string[] dmnt_stringArrayIntersection(string $array1[], string $array2[])
{
    string $myIntersector = `stringArrayIntersector`;
    string $intersection[];

    stringArrayIntersector -edit -intersect $array1 $myIntersector;
    stringArrayIntersector -edit -intersect $array2 $myIntersector;

    $intersection = `stringArrayIntersector -query $myIntersector`;

    stringArrayIntersector -edit -reset $myIntersector;
    deleteUI $myIntersector;
    return $intersection;
}

global proc int dmnt_isEdgeHard(string $edge)
{
    string $edgeVertexFaces[] = sort(ls("-l", "-fl", polyListComponentConversion("-tvf", $edge)));

    if (size($edgeVertexFaces) != 4)
        return 1;

    else
    {
        vector $n0 = polyNormalPerVertex("-q", "-xyz", $edgeVertexFaces[0]);
        vector $n1 = polyNormalPerVertex("-q", "-xyz", $edgeVertexFaces[1]);
        vector $n2 = polyNormalPerVertex("-q", "-xyz", $edgeVertexFaces[2]);
        vector $n3 = polyNormalPerVertex("-q", "-xyz", $edgeVertexFaces[3]);

        if ($n0 != $n1 || $n2 != $n3)           
            return 1;
    }

    return 0;
}

global proc dmnt_unlockNormals()
{
    string $selection[] = ls("-sl", "-l", "-fl");
    string $selectedObjects[] = ls("-sl", "-l", "-o");

    for ($obj in $selectedObjects)
    {
        string $objSelection[] = ls("-sl", "-l", "-fl", $obj);
        string $objAllEdges[] = ls("-l", "-fl", polyListComponentConversion("-te", "-vfa", $objSelection));
        string $objVertexFaces[] = ls("-l", "-fl", polyListComponentConversion("-tvf", $objSelection));
        string $objHardEdges[];
        
        for ($edge in $objAllEdges)
            if (dmnt_isEdgeHard($edge))
                $objHardEdges[size($objHardEdges)] = $edge;

        polyNormalPerVertex -ufn 1 $objVertexFaces;
        if (size($objHardEdges))
            $objAllEdges = stringArrayRemove($objHardEdges, $objAllEdges);
        if (size($objAllEdges))
            polySoftEdge -a 360 $objAllEdges;
    }

    select -r $selection;
    print("Vertex normals have been unlocked\n");
}

global proc dmnt_lockNormals()
{
    string $selection[] = ls("-sl", "-l", "-fl");
    string $selectedObjects[] = ls("-sl", "-l", "-o");

    for ($obj in $selectedObjects)
    {
        string $objSelection[] = ls("-sl", "-l", "-fl", $obj);
        string $vertexFaces[] = ls("-l", "-fl", polyListComponentConversion("-tvf", $objSelection));
        string $softEdges[] = dmnt_getEdges($objSelection, 0);
        
        polyNormalPerVertex -fn 1 $vertexFaces;

    if (size($softEdges) > 0)
        polySoftEdge -a 360 $softEdges;
    }

    select -r $selection;
    print("Vertex normals have been locked\n");
}

global proc dmnt()
{
    int $showNormal = 0;
    float $normalSize = 5.0;

    int $showNormalCurrent[] = `polyOptions -q -dn -gl`;
    for ($int in $showNormalCurrent)
    {
        if ($int == 1)
        {
            $showNormal = 1;
            break;
        }
    }

    float $normalSizeCurrent[] = `polyOptions -q -sn -gl`;
    if ($normalSizeCurrent[0] > 0.4)
        $normalSize = $normalSizeCurrent[0];

    dmnt_showUI($showNormal, $normalSize);
    dmnt_onSettingsChanged();
    scriptJob -e "SelectionChanged" "dmnt_onSettingsChanged()" -p DMNTwin;
}

dmnt();