string $gsToolDir = "//192.168.1.10/Softwares/Technical_Script/Maya_2018/MayaTools/scripts"; 
string $MAYA_SCRIPT_PATH ; 
////// 
$MAYA_SCRIPT_PATH += $gsToolDir; 
$PYTHONPATH   = "//192.168.1.10/Softwares/Technical_Script/Maya_2018/MayaTools/scripts" ; 
  
putenv "MAYA_SCRIPT_PATH"  (`getenv MAYA_SCRIPT_PATH` + ";" + $MAYA_SCRIPT_PATH); 
putenv "PYTHONPATH"  (`getenv PYTHONPATH` + ";" + $PYTHONPATH); 
 
////// 
 
eval ("source \"" + $MAYA_SCRIPT_PATH + "/GS_tools.mel\""); 
python("import zhcg_polyTools; reload(zhcg_polyTools)"); 
evalDeferred("source \"GN_ImportExport/GN_ImportExport.mel\"; GN_ImportExport"); 
