// =====================================================================
//  DM Normal Tools
//  Version: 1.0.0
//  Author: Dmytro Lystopad
//  Description: A tool for aligning vertex normals in Maya.
//               Includes face-weighted and average normal algorithms.
//               The "Keep Hard Edges" option preserves shading on hard edges, keeping them visually sharp.
//               Normal values can be copied and pasted via the UI.
//               Supports aligning normals on single and multiple objects simultaneously, or selected components (vertices, faces, or vertex faces).
// =====================================================================

global proc GS_Normal_Tools_UI()
{
    if (`window -exists DMNTwin`)
        deleteUI DMNTwin;

    int $displayNormalsInitValue;
    if (size(ls( "-sl")) > 0)
    {
        int $tmp[] = (`polyOptions -q -dn`);
        $displayNormalsInitValue = $tmp[0];
    }
    else {
        int $tmp[] = (`polyOptions -q -dn -gl`);
        $displayNormalsInitValue = $tmp[0];
    }

    window -t "GS Normal Tools"-rtf 1 -s 0 DMNTwin;

    columnLayout -adj 1 -cat "both" 0;
        frameLayout -l "Align Normals" -bgs 1;
            rowLayout -nc 2 -adj 2 -rat 1 "both" 5 -cat 1 "both" 0;
                columnLayout -adj 1 -cat "both" 0;
                    radioButtonGrp -numberOfRadioButtons 2 -labelArray2 "Average" "Face Weighted" -an1 "For each vertex, the script assigns an average normal calculated based on the normals of neighboring faces." -an2 "For each vertex, the script takes the full normal of the face that has the largest area among all faces that use that vertex." -select 2 -vr alignMethodRBG;
                    checkBox -label "Keep Hard Edges" -ann "Preserve the shading for hard edges so they still appear sharp." keepHardEdgesCB;
                setParent ..;
                rowLayout -nc 1 -adj 1;
                    button -label "Align Normals" -command "dmnt_alignNormalsFromUI()" -ann "Select an object or its component to align vertex normals" -h 55 alignNormalsBTN;
                setParent  ..;
            setParent  ..;
        setParent  ..;
        frameLayout -l "Adjust Normals" -bgs 1;
            columnLayout -adj 1 -cat "both" 0;
                rowLayout -nc 3;
                    floatFieldGrp -numberOfFields 3 -value1 0 -value2 0 -value3 0 -pre 6 -ann "X, Y and Z values of the normal" normalFFG;
                    button -label "Get" -command "dmnt_copyNormalFromUI()" getNormalBTN;
                    button -label "Set" -command "dmnt_pasteNormalFromUI()" setNormalBTN;
                setParent ..;
                rowLayout -nc 1 -adj 1;
                    button -label "Average from Edge" -command "dmnt_alignNormalsOnEdgeFormUI()" -ann "Apply average normal from connected faces to vertices of the selected edge" averageFromEdgeBTN;
                setParent ..;
            setParent ..;
        setParent  ..;

        frameLayout -l "Selection" -bgs 1;
            columnLayout -adj 1 -cat "both" 0;
                button -label "Select Hard Edges" -command "dmnt_SelectEdgesFromUI(1)" selectHardEdgesBTN;
                button -label "Select Soft Edges" -command "dmnt_SelectEdgesFromUI(0)" selectSoftEdgesBTN;
                button -label "Convert to Vertex Faces" -command "dmnt_SelectVertexFacesFromUI" selectVertexFacesBTN;

            setParent ..;
        setParent  ..;  

        frameLayout -l "Display options" -bgs 1;
                columnLayout -adj 1 -cat "both" 0;
                    checkBox -label "Show Vertex Normals" -ann "Enables displaying vertex normals" -cc "dmnt_OnSettingsChanged()" -v $displayNormalsInitValue showNormalsCB;
                    intSliderGrp -label "Normal Size:" -cal 1 "left" -field 1 -min 1 -max 25 -fieldMinValue 0 -fieldMaxValue 100 -value 5 -cw3 70 70 50 -cc "dmnt_OnSettingsChanged()" normalSizeISG;
                setParent  ..;
        setParent  ..;
        
        columnLayout -adj 1 -cat "both" 0 -en 0;
        separator;
            text -l "GS Normal Tools v1.0.0" -al "center";
        separator;
        setParent  ..;
    setParent  ..;

    dimWhen -false SomethingSelected alignNormalsBTN;
    dimWhen -false SomethingSelected getNormalBTN;
    dimWhen -false SomethingSelected setNormalBTN;
    dimWhen -false SomethingSelected averageFromEdgeBTN;
    dimWhen -false SomethingSelected selectHardEdgesBTN;
    dimWhen -false SomethingSelected selectSoftEdgesBTN;
    dimWhen -false SomethingSelected selectVertexFacesBTN;

    showWindow DMNTwin;
}

global proc dmnt_copyNormalFromUI()
{
    vector $normal = dmnt_getNormalFromComponents(ls("-sl", "-fl", "-l"));
    floatFieldGrp -e -v1 ($normal.x) -v2 ($normal.y) -v3 ($normal.z) normalFFG;
}
global proc dmnt_pasteNormalFromUI()
{   
    string $selection[] = ls( "-sl", "-fl", "-l");
    string $selectedVerticies[] = filterExpand("-sm", 31, $selection);
    string $softEdges[] = dmnt_getSoftEdges($selectedVerticies);
    vector $normal = `floatFieldGrp -q -v normalFFG`;

    polyNormalPerVertex -xyz ($normal.x) ($normal.y) ($normal.z) (ls("-fl", "-l", polyListComponentConversion("-tvf", $selection)));

    if (size($selectedVerticies) > 0 && size($softEdges) > 0)
    {
        polySoftEdge -a 360 $softEdges;
        select -r $selection;
    }
}

global proc dmnt_OnSettingsChanged()
{
    int $showNormal = `checkBox -q -v showNormalsCB`;       
    int $normalSize = `intSliderGrp -q -v normalSizeISG`;
    
    polyOptions -dn $showNormal -pt -sn $normalSize -gl;
}

global proc dmnt_SelectEdgesFromUI(int $hardEdges)
{
    string $edges[];

    if ($hardEdges)
        $edges = dmnt_getHardEdges(ls("-sl", "-fl", "-l"));
    else
        $edges = dmnt_getSoftEdges(ls("-sl", "-fl", "-l"));

    select -r $edges;
}

global proc dmnt_SelectVertexFacesFromUI()
{
    select("-r", polyListComponentConversion("-tvf"));
}

global proc dmnt_alignNormalsOnEdgeFormUI()
{
    string $edges[] = ls( "-sl", "-fl", "-l", filterExpand("-sm", 32) );
    dmnt_setAverageNormalFromEdges($edges);
}
global proc dmnt_alignNormalsFromUI() {
    int $method = `radioButtonGrp -q -select alignMethodRBG`;
    int $keepHardEdges = `checkBox -q -value keepHardEdgesCB`;
    dmnt_alignVertexNormals($method, $keepHardEdges);
}

global proc dmnt_alignVertexNormals(int $method, int $keepHardEdges)
{
    string $selection[] = `ls -sl -l`;
    string $selectedShapes[] = ls("-dag", "-lf", ls("-o", $selection));
    string $hardEdges[];
    
    if (size($selection) == 0)
        error "Please select a mesh or components.";
    
    for ($shape in $selectedShapes)
        if (`objectType $shape` != "mesh")
            error "Selection is not a mesh.";

    string $vertices[] = ls( "-fl", "-l", (polyListComponentConversion("-tv")));

    if ($keepHardEdges)
        $hardEdges = dmnt_getHardEdges($selection);

    for ($vertex in $vertices)
    {
        string $connectedFaces[] = ls( "-fl", "-l", (polyListComponentConversion("-fv", "-tf", $vertex)));
        vector $normal;

        if ($method == 2)
            $normal = dmnt_getNormalFromFace(dmnt_getLargestFace($connectedFaces));

        else
            $normal = dmnt_getNormalFromFaces($connectedFaces);

        polyNormalPerVertex -xyz ($normal.x) ($normal.y) ($normal.z) $vertex;
        
        if ($keepHardEdges && dmnt_isVertexOnHardEdge($vertex, $hardEdges)) {
            dmnt_alignVertexOnHardEdge($vertex, $method);
        }
    }

    select -r $selection;
    //DeleteHistory;
    print "Vertex normals aligned.\n";
}

global proc dmnt_setAverageNormalFromEdges(string $edges[])
{
    for ($edge in $edges)
    {
        string $connectedFaces[] = ls( "-fl", "-l", (polyListComponentConversion("-fe", "-tf", $edge)));
        vector $normal = dmnt_getNormalFromFaces($connectedFaces);
        string $vertices[] = ls( "-fl", "-l", (polyListComponentConversion("-fe", "-tv", $edge)));

        for ($vertex in $vertices)
            polyNormalPerVertex -xyz ($normal.x) ($normal.y) ($normal.z) $vertex;
    }
}

global proc vector dmnt_getNormalFromFace(string $face)
{
    vector $normal;
    float $nx, $ny, $nz;
    string $polyInfo[] = `polyInfo -fn $face`;
    string $tokens[];
    
    tokenize $polyInfo[0] $tokens;
    $nx = $tokens[2];
    $ny = $tokens[3];
    $nz = $tokens[4];
    $normal = unit(<<$nx, $ny, $nz>>);

    return $normal;
}

global proc string dmnt_getLargestFace(string $faceList[])
{
    string $largestFace;
    float $largestArea = 0;

    for($face in $faceList)
    {
        float $area[] = `polyEvaluate -wfa $face`;

        if($area[0] > $largestArea)
        {
            $largestArea = $area[0];
            $largestFace = $face;
        }
    }
    return $largestFace;
}

global proc string[] dmnt_getHardEdges(string $selection[])
{
    string $hardEdges[];
    string $allEdges[] = ls("-fl", "-l", polyListComponentConversion("-te", $selection));

    for ($e = 0; $e < size($allEdges); $e++)
    {
        string $edgeInfo[] = `polyInfo -ev $allEdges[$e]`;

        if (`gmatch $edgeInfo[0] "*Hard*"`)
            $hardEdges[size($hardEdges)] = $allEdges[$e];
    }

    return $hardEdges;
}

global proc string[] dmnt_getSoftEdges(string $selection[])
{
    string $hardEdges[] = dmnt_getHardEdges($selection);
    string $allEdges[] = ls("-fl", "-l", polyListComponentConversion("-te", $selection));

    return stringArrayRemove($hardEdges, $allEdges);
}

global proc int dmnt_isVertexOnHardEdge(string $vertex, string $hardEdges[]) {
    string $connectedEdges[] = ls("-fl", "-l", (polyListComponentConversion("-te", $vertex)));

    for ($edge in $connectedEdges)
        if (stringArrayContains($edge, $hardEdges))
            return 1;

    return 0;
}

global proc dmnt_alignVertexOnHardEdge(string $vertex, int $method)
{
    string $vertexFaces[] = ls("-fl", "-l", (polyListComponentConversion("-tvf", $vertex)));
    string $vertexEdges[] = ls("-fl", "-l", polyListComponentConversion("-fv", "-te", $vertex) );
    string $vertexHardEdges[] = dmnt_getHardEdges( {$vertex} );
    string $vertexSoftEdges[] = stringArrayRemove($vertexHardEdges, ls("-fl", "-l", polyListComponentConversion("-fv", "-te", $vertex)));
    vector $normal;

    for ($vertexFace in $vertexFaces)
    {
        string $face[] = ls( "-fl", "-l", (polyListComponentConversion("-fvf", "-tf", $vertexFace)));
        string $faces[] = ls( "-fl", "-l", (polyListComponentConversion("-fv", "-tf", $vertex)));
        string $connectedFaces[] = dmnt_getNeighborFaces($face[0], $faces);

        if ($method == 2) {
            string $largestFace =  (size($connectedFaces)>0?dmnt_getLargestFace($connectedFaces):$face[0]);
            $normal = dmnt_getNormalFromFace($largestFace);
        }
        else
            $normal = dmnt_getNormalFromFaces($connectedFaces);

        polyNormalPerVertex -xyz ($normal.x) ($normal.y) ($normal.z) $vertexFace;
    }

    if (size($vertexSoftEdges) > 0)
        polySoftEdge -a 360 $vertexSoftEdges;
}

global proc string[] dmnt_getNeighborFaces(string $faceStart, string $faces[])
{    
    string $neighbors[];
    string $facesEdges[] = ls("-fl", "-l", polyListComponentConversion("-ff", "-te", "-in", $faces) );
    string $faceStartHardEdges[] = dmnt_getHardEdges( {$faceStart} );
    string $faceStartSoftEdges[] = stringArrayRemove($faceStartHardEdges, ls("-fl", "-l", polyListComponentConversion("-ff", "-te", $faceStart)));

    string $commonSoftEdges[] = dmnt_stringArrayIntersection($faceStartSoftEdges, $facesEdges);

    $neighbors = ls("-fl", "-l", polyListComponentConversion("-fe", "-tf", $commonSoftEdges) );
    $neighbors[size($neighbors)] = $faceStart;

    return (stringArrayRemoveDuplicates($neighbors));
}

global proc vector dmnt_getNormalFromVertices(string $vertices[])
{
    $vertices = ls("-fl", "-l", filterExpand("-sm", 31, $vertices));
    vector $normal = <<0, 0, 0>>;
    float $normals[] = `polyNormalPerVertex -q -xyz $vertices`;
    
    for ($i = 0; $i < size($normals); $i += 3)
        $normal += << $normals[$i], $normals[$i + 1], $normals[$i + 2] >>;
    
    return unit($normal/size($normals)/3);
}

global proc vector dmnt_getNormalFromVertexFaces(string $vertexFaces[])
{
    $vertexFaces = ls("-fl", "-l", filterExpand("-sm", 70, $vertexFaces));
    vector $normal = <<0, 0, 0>>;
        
    if (size($vertexFaces) > 1)
    {
        for ($vertexFace in $vertexFaces)
            $normal += `polyNormalPerVertex -q -xyz $vertexFace`;
            
        $normal = unit($normal/size($vertexFaces));
    }
    else $normal = `polyNormalPerVertex -q -xyz $vertexFaces[0]`;
    
    return $normal;
}

global proc vector dmnt_getNormalFromFaces(string $faces[])
{
    $faces = ls("-fl", "-l", filterExpand("-sm", 34, $faces));
    vector $normal = <<0, 0, 0>>;
            
    for ($face in $faces)    
        $normal += dmnt_getNormalFromFace($face);

    return (size($faces) > 0 ? unit ($normal / size($faces)) : $normal);
}

global proc vector dmnt_getNormalFromComponents(string $components[])
{   
    if (size(filterExpand("-sm", 31, $components)) > 0) //Vertex
        return dmnt_getNormalFromVertices($components);
    else if (size(filterExpand("-sm", 34, $components)) > 0) //Face
        return dmnt_getNormalFromFaces($components);
    else if (size(filterExpand("-sm", 70, $components)) > 0) //Vertex Face
        return dmnt_getNormalFromVertexFaces($components);
    
    else return <<0, 0, 0>>;
}

global proc string[] dmnt_stringArrayIntersection(string $array1[], string $array2[])
{
    string $myIntersector = `stringArrayIntersector`;
    string $intersection[];

    stringArrayIntersector -edit -intersect $array1 $myIntersector;
    stringArrayIntersector -edit -intersect $array2 $myIntersector;

    $intersection = `stringArrayIntersector -query $myIntersector`;

    stringArrayIntersector -edit -reset $myIntersector;
    deleteUI $myIntersector;
    return $intersection;
}

GS_Normal_Tools_UI();