HIVE_BIPED_STRD_OPTIONS = {"autoRightSide": True,
                           "leftIdentifier": "_L",
                           "rightIdentifier": "_R",
                           "maintainOffset": True,
                           "leftRightUnderscore": False,
                           "leftRightPrefix": False,
                           "leftRightSuffix": False}

HIVE_BIPED_STRD_CTRLS = [{'root': {'node': 'spine_M_cog_anim', 'constraint': 'parent'}},
                         {'shoulder_L': {'node': 'arm_L_shldr_fk_anim', 'constraint': 'orient'}},
                         {'elbow_L': {'node': 'arm_L_elbow_fk_anim', 'constraint': 'orient'}},
                         {'wrist_L': {'node': 'arm_L_wrist_fk_anim', 'constraint': 'orient'}},
                         {'thigh_L': {'node': 'leg_L_upr_fk_anim', 'constraint': 'orient'}},
                         {'knee_L': {'node': 'leg_L_knee_fk_anim', 'constraint': 'orient'}},
                         {'ankle_L': {'node': 'leg_L_foot_fk_anim', 'constraint': 'orient'}},
                         {'ball_L': {'node': 'leg_L_ball_fk_anim', 'constraint': 'orient'}},
                         {'clavicle_L': {'node': 'clavicle_L_00_anim', 'constraint': 'orient'}},
                         {'neck01': {'node': 'head_M_neck_anim', 'constraint': 'orient'}},
                         {'neck02': {'node': '', 'constraint': 'orient'}},
                         {'head': {'node': 'head_M_head_anim', 'constraint': 'orient'}},
                         {'spine00': {'node': 'spine_M_ctrl00_anim', 'constraint': 'parent'}},
                         {'spine01': {'node': 'spine_M_ctrl01_anim', 'constraint': 'parent'}},
                         {'spine02': {'node': 'spine_M_ctrl02_anim', 'constraint': 'parent'}},
                         {'spine03': {'node': 'spine_M_ctrl03_anim', 'constraint': 'parent'}},
                         {'spine04': {'node': 'spine_M_ctrl04_anim', 'constraint': 'parent'}},
                         {'spine05': {'node': 'spine_M_ctrl05_anim', 'constraint': 'parent'}},
                         {'spine06': {'node': 'spine_M_ctrl06_anim', 'constraint': 'parent'}},
                         {'spine07': {'node': 'spine_M_ctrl07_anim', 'constraint': 'parent'}},
                         {'spine08': {'node': 'spine_M_ctrl08_anim', 'constraint': 'parent'}},
                         {'spine09': {'node': 'spine_M_ctrl09_anim', 'constraint': 'parent'}},
                         {'spine10': {'node': 'spine_M_ctrl10_anim', 'constraint': 'parent'}},
                         {'thumb01_L': {'node': 'finger_thumb_L_00_anim', 'constraint': 'orient'}},
                         {'thumb02_L': {'node': 'finger_thumb_L_01_anim', 'constraint': 'orient'}},
                         {'thumb03_L': {'node': 'finger_thumb_L_02_anim', 'constraint': 'orient'}},
                         {'indexMetacarpal_L': {'node': 'finger_pointer_L_00_anim', 'constraint': 'orient'}},
                         {'index01_L': {'node': 'finger_pointer_L_01_anim', 'constraint': 'orient'}},
                         {'index02_L': {'node': 'finger_pointer_L_02_anim', 'constraint': 'orient'}},
                         {'index03_L': {'node': 'finger_pointer_L_03_anim', 'constraint': 'orient'}},
                         {'middleMetacarpal_L': {'node': 'finger_middle_L_00_anim', 'constraint': 'orient'}},
                         {'middle01_L': {'node': 'finger_middle_L_01_anim', 'constraint': 'orient'}},
                         {'middle02_L': {'node': 'finger_middle_L_02_anim', 'constraint': 'orient'}},
                         {'middle03_L': {'node': 'finger_middle_L_03_anim', 'constraint': 'orient'}},
                         {'ringMetacarpal_L': {'node': 'finger_ring_L_00_anim', 'constraint': 'orient'}},
                         {'ring01_L': {'node': 'finger_ring_L_01_anim', 'constraint': 'orient'}},
                         {'ring02_L': {'node': 'finger_ring_L_02_anim', 'constraint': 'orient'}},
                         {'ring03_L': {'node': 'finger_ring_L_03_anim', 'constraint': 'orient'}},
                         {'pinkyMetacarpal_L': {'node': 'finger_pinky_L_00_anim', 'constraint': 'orient'}},
                         {'pinky01_L': {'node': 'finger_pinky_L_01_anim', 'constraint': 'orient'}},
                         {'pinky02_L': {'node': 'finger_pinky_L_02_anim', 'constraint': 'orient'}},
                         {'pinky03_L': {'node': 'finger_pinky_L_03_anim', 'constraint': 'orient'}}
                         ]

HIVE_BIPED_LIGHT_CTRLS = list(HIVE_BIPED_STRD_CTRLS)  # Use STRD ctrls just change spine and root
HIVE_BIPED_LIGHT_CTRLS[0] = {'root': {'node': 'spine_M_cog_anim', 'constraint': 'parent'}}
HIVE_BIPED_LIGHT_CTRLS[12] = {'spine00': {'node': 'spine_M_01_anim', 'constraint': 'orient'}}
HIVE_BIPED_LIGHT_CTRLS[13] = {'spine01': {'node': '', 'constraint': 'orient'}}
HIVE_BIPED_LIGHT_CTRLS[14] = {'spine02': {'node': 'spine_M_02_anim', 'constraint': 'orient'}}

HIVE_BIPED_UE_OPTIONS = {"autoRightSide": True,
                         "leftIdentifier": "_l_",
                         "rightIdentifier": "_r_",
                         "maintainOffset": True,
                         "leftRightUnderscore": False,
                         "leftRightPrefix": False,
                         "leftRightSuffix": False}

HIVE_BIPED_UE_CTRLS = [{'root': {'node': 'spine_m_hipsSwing_anim', 'constraint': 'parent'}},
                       {'shoulder_L': {'node': 'arm_l_upperarm_fk_anim', 'constraint': 'orient'}},
                       {'elbow_L': {'node': 'arm_l_lowerarm_fk_anim', 'constraint': 'orient'}},
                       {'wrist_L': {'node': 'arm_l_hand_fk_anim', 'constraint': 'orient'}},
                       {'thigh_L': {'node': 'leg_l_thigh_fk_anim', 'constraint': 'orient'}},
                       {'knee_L': {'node': 'leg_l_calf_fk_anim', 'constraint': 'orient'}},
                       {'ankle_L': {'node': 'leg_l_foot_fk_anim', 'constraint': 'orient'}},
                       {'ball_L': {'node': 'leg_l_ball_fk_anim', 'constraint': 'orient'}},
                       {'clavicle_L': {'node': 'clavicle_l_00_anim', 'constraint': 'orient'}},
                       {'neck01': {'node': 'head_m_neck_01_anim', 'constraint': 'orient'}},
                       {'neck02': {'node': '', 'constraint': 'orient'}},
                       {'head': {'node': 'head_m_head_anim', 'constraint': 'orient'}},
                       {'spine00': {'node': 'spine_m_03_anim', 'constraint': 'parent'}},
                       {'spine01': {'node': 'spine_m_04_anim', 'constraint': 'parent'}},
                       {'spine02': {'node': 'spine_m_05_anim', 'constraint': 'parent'}},
                       {'spine03': {'node': '', 'constraint': 'parent'}},
                       {'spine04': {'node': '', 'constraint': 'parent'}},
                       {'spine05': {'node': '', 'constraint': 'parent'}},
                       {'spine06': {'node': '', 'constraint': 'parent'}},
                       {'spine07': {'node': '', 'constraint': 'parent'}},
                       {'spine08': {'node': '', 'constraint': 'parent'}},
                       {'spine09': {'node': '', 'constraint': 'parent'}},
                       {'spine10': {'node': '', 'constraint': 'parent'}},
                       {'thumb01_L': {'node': 'thumb_l_metacarpal_anim', 'constraint': 'orient'}},
                       {'thumb02_L': {'node': 'thumb_l_01_anim', 'constraint': 'orient'}},
                       {'thumb03_L': {'node': 'thumb_l_02_anim', 'constraint': 'orient'}},
                       {'indexMetacarpal_L': {'node': 'index_l_metacarpal_anim', 'constraint': 'orient'}},
                       {'index01_L': {'node': 'index_l_01_anim', 'constraint': 'orient'}},
                       {'index02_L': {'node': 'index_l_02_anim', 'constraint': 'orient'}},
                       {'index03_L': {'node': 'index_l_03_anim', 'constraint': 'orient'}},
                       {'middleMetacarpal_L': {'node': 'middle_l_metacarpal_anim', 'constraint': 'orient'}},
                       {'middle01_L': {'node': 'middle_l_01_anim', 'constraint': 'orient'}},
                       {'middle02_L': {'node': 'middle_l_02_anim', 'constraint': 'orient'}},
                       {'middle03_L': {'node': 'middle_l_03_anim', 'constraint': 'orient'}},
                       {'ringMetacarpal_L': {'node': 'ring_l_metacarpal_anim', 'constraint': 'orient'}},
                       {'ring01_L': {'node': 'ring_l_01_anim', 'constraint': 'orient'}},
                       {'ring02_L': {'node': 'ring_l_02_anim', 'constraint': 'orient'}},
                       {'ring03_L': {'node': 'ring_l_03_anim', 'constraint': 'orient'}},
                       {'pinkyMetacarpal_L': {'node': 'pinky_l_metacarpal_anim', 'constraint': 'orient'}},
                       {'pinky01_L': {'node': 'pinky_l_01_anim', 'constraint': 'orient'}},
                       {'pinky02_L': {'node': 'pinky_l_02_anim', 'constraint': 'orient'}},
                       {'pinky03_L': {'node': 'pinky_l_03_anim', 'constraint': 'orient'}}
                       ]

SKELE_BUILDER_OPTIONS = {"autoRightSide": True,
                         "leftIdentifier": "L",
                         "rightIdentifier": "R",
                         "maintainOffset": True,
                         "leftRightUnderscore": True,
                         "leftRightPrefix": False,
                         "leftRightSuffix": False}

SKELE_BUILDER_CTRLS = [{'root': {'node': 'rootControl', 'constraint': 'parent'}},
                       {'shoulder_L': {'node': 'fk_bicepControl_L', 'constraint': 'orient'}},
                       {'elbow_L': {'node': 'fk_elbowControl_L', 'constraint': 'orient'}},
                       {'wrist_L': {'node': 'fk_wristControl_L', 'constraint': 'orient'}},
                       {'thigh_L': {'node': 'fk_thighControl_L', 'constraint': 'orient'}},
                       {'knee_L': {'node': 'fk_kneeControl_L', 'constraint': 'orient'}},
                       {'ankle_L': {'node': 'fk_ankleControl_L', 'constraint': 'orient'}},
                       {'ball_L': {'node': '', 'constraint': 'orient'}},
                       {'clavicle_L': {'node': 'clavicleControl_L', 'constraint': 'orient'}},
                       {'neck01': {'node': 'neckControl', 'constraint': 'orient'}},
                       {'neck02': {'node': '', 'constraint': 'orient'}},
                       {'head': {'node': 'headControl', 'constraint': 'orient'}},
                       {'spine00': {'node': 'spine_0_fkControl', 'constraint': 'parent'}},
                       {'spine01': {'node': 'spine_1_fkControl', 'constraint': 'parent'}},
                       {'spine02': {'node': 'spine_3_fkControl', 'constraint': 'parent'}},
                       {'spine03': {'node': '', 'constraint': 'parent'}},
                       {'spine04': {'node': '', 'constraint': 'parent'}},
                       {'spine05': {'node': '', 'constraint': 'parent'}},
                       {'spine06': {'node': '', 'constraint': 'parent'}},
                       {'spine07': {'node': '', 'constraint': 'parent'}},
                       {'spine08': {'node': '', 'constraint': 'parent'}},
                       {'spine09': {'node': '', 'constraint': 'parent'}},
                       {'spine10': {'node': '', 'constraint': 'parent'}},
                       {'thumb01_L': {'node': 'ThumbControl_0_L', 'constraint': 'orient'}},
                       {'thumb02_L': {'node': 'ThumbControl_1_L', 'constraint': 'orient'}},
                       {'thumb03_L': {'node': 'ThumbControl_2_L', 'constraint': 'orient'}},
                       {'indexMetacarpal_L': {'node': 'IndexControl_0_L', 'constraint': 'orient'}},
                       {'index01_L': {'node': 'IndexControl_1_L', 'constraint': 'orient'}},
                       {'index02_L': {'node': 'IndexControl_2_L', 'constraint': 'orient'}},
                       {'index03_L': {'node': 'IndexControl_3_L', 'constraint': 'orient'}},
                       {'middleMetacarpal_L': {'node': 'MidControl_0_L', 'constraint': 'orient'}},
                       {'middle01_L': {'node': 'MidControl_1_L', 'constraint': 'orient'}},
                       {'middle02_L': {'node': 'MidControl_2_L', 'constraint': 'orient'}},
                       {'middle03_L': {'node': 'MidControl_3_L', 'constraint': 'orient'}},
                       {'ringMetacarpal_L': {'node': 'RingControl_0_L', 'constraint': 'orient'}},
                       {'ring01_L': {'node': 'RingControl_1_L', 'constraint': 'orient'}},
                       {'ring02_L': {'node': 'RingControl_2_L', 'constraint': 'orient'}},
                       {'ring03_L': {'node': 'RingControl_3_L', 'constraint': 'orient'}},
                       {'pinkyMetacarpal_L': {'node': 'PinkyControl_0_L', 'constraint': 'orient'}},
                       {'pinky01_L': {'node': 'PinkyControl_1_L', 'constraint': 'orient'}},
                       {'pinky02_L': {'node': 'PinkyControl_2_L', 'constraint': 'orient'}},
                       {'pinky03_L': {'node': 'PinkyControl_3_L', 'constraint': 'orient'}}
                       ]

SKELE_BUILDER_JOINTS = [{'root': {'node': 'root', 'constraint': 'parent'}},
                        {'shoulder_L': {'node': 'L_bicep', 'constraint': 'orient'}},
                        {'elbow_L': {'node': 'L_elbow', 'constraint': 'orient'}},
                        {'wrist_L': {'node': 'L_wrist', 'constraint': 'orient'}},
                        {'thigh_L': {'node': 'L_leg01', 'constraint': 'orient'}},
                        {'knee_L': {'node': 'L_leg02', 'constraint': 'orient'}},
                        {'ankle_L': {'node': 'L_leg03', 'constraint': 'orient'}},
                        {'ball_L': {'node': 'L_toeBase', 'constraint': 'orient'}},
                        {'clavicle_L': {'node': 'L_clavicle', 'constraint': 'orient'}},
                        {'neck01': {'node': 'neck1', 'constraint': 'orient'}},
                        {'neck02': {'node': '', 'constraint': 'orient'}},
                        {'head': {'node': 'head', 'constraint': 'orient'}},
                        {'spine00': {'node': 'spine2', 'constraint': 'parent'}},
                        {'spine01': {'node': 'spine3', 'constraint': 'parent'}},
                        {'spine02': {'node': 'spine5', 'constraint': 'parent'}},
                        {'spine03': {'node': '', 'constraint': 'parent'}},
                        {'spine04': {'node': '', 'constraint': 'parent'}},
                        {'spine05': {'node': '', 'constraint': 'parent'}},
                        {'spine06': {'node': '', 'constraint': 'parent'}},
                        {'spine07': {'node': '', 'constraint': 'parent'}},
                        {'spine08': {'node': '', 'constraint': 'parent'}},
                        {'spine09': {'node': '', 'constraint': 'parent'}},
                        {'spine10': {'node': '', 'constraint': 'parent'}},
                        {'thumb01_L': {'node': 'Thumb_0_L', 'constraint': 'orient'}},
                        {'thumb02_L': {'node': 'Thumb_1_L', 'constraint': 'orient'}},
                        {'thumb03_L': {'node': 'Thumb_2_L', 'constraint': 'orient'}},
                        {'indexMetacarpal_L': {'node': 'Index_0_L', 'constraint': 'orient'}},
                        {'index01_L': {'node': 'Index_1_L', 'constraint': 'orient'}},
                        {'index02_L': {'node': 'Index_2_L', 'constraint': 'orient'}},
                        {'index03_L': {'node': 'Index_3_L', 'constraint': 'orient'}},
                        {'middleMetacarpal_L': {'node': 'Mid_0_L', 'constraint': 'orient'}},
                        {'middle01_L': {'node': 'Mid_1_L', 'constraint': 'orient'}},
                        {'middle02_L': {'node': 'Mid_2_L', 'constraint': 'orient'}},
                        {'middle03_L': {'node': 'Mid_3_L', 'constraint': 'orient'}},
                        {'ringMetacarpal_L': {'node': 'Ring_0_L', 'constraint': 'orient'}},
                        {'ring01_L': {'node': 'Ring_1_L', 'constraint': 'orient'}},
                        {'ring02_L': {'node': 'Ring_2_L', 'constraint': 'orient'}},
                        {'ring03_L': {'node': 'Ring_3_L', 'constraint': 'orient'}},
                        {'pinkyMetacarpal_L': {'node': 'Pinky_0_L', 'constraint': 'orient'}},
                        {'pinky01_L': {'node': 'Pinky_1_L', 'constraint': 'orient'}},
                        {'pinky02_L': {'node': 'Pinky_2_L', 'constraint': 'orient'}},
                        {'pinky03_L': {'node': 'Pinky_3_L', 'constraint': 'orient'}}
                        ]

HIK_OPTIONS = {"autoRightSide": True,
               "leftIdentifier": "Left",
               "rightIdentifier": "Right",
               "maintainOffset": True,
               "leftRightUnderscore": False,
               "leftRightPrefix": False,
               "leftRightSuffix": False}

HIK_JOINTS = [{'root': {'node': 'Hips', 'constraint': 'parent'}},
              {'shoulder_L': {'node': 'LeftArm', 'constraint': 'orient'}},
              {'elbow_L': {'node': 'LeftForeArm', 'constraint': 'orient'}},
              {'wrist_L': {'node': 'LeftHand', 'constraint': 'orient'}},
              {'thigh_L': {'node': 'LeftUpLeg', 'constraint': 'orient'}},
              {'knee_L': {'node': 'LeftLeg', 'constraint': 'orient'}},
              {'ankle_L': {'node': 'LeftFoot', 'constraint': 'orient'}},
              {'ball_L': {'node': 'LeftToeBase', 'constraint': 'orient'}},
              {'clavicle_L': {'node': 'LeftShoulder', 'constraint': 'orient'}},
              {'neck01': {'node': 'Neck', 'constraint': 'orient'}},
              {'neck02': {'node': '', 'constraint': 'orient'}},
              {'head': {'node': 'Head', 'constraint': 'orient'}},
              {'spine00': {'node': 'Hips', 'constraint': 'orient'}},
              {'spine01': {'node': 'Spine', 'constraint': 'orient'}},
              {'spine02': {'node': 'Spine2', 'constraint': 'orient'}},
              {'spine03': {'node': '', 'constraint': 'orient'}},
              {'spine04': {'node': '', 'constraint': 'orient'}},
              {'spine05': {'node': '', 'constraint': 'orient'}},
              {'spine06': {'node': '', 'constraint': 'orient'}},
              {'spine07': {'node': '', 'constraint': 'orient'}},
              {'spine08': {'node': '', 'constraint': 'orient'}},
              {'spine09': {'node': '', 'constraint': 'orient'}},
              {'spine10': {'node': '', 'constraint': 'orient'}},
              {'thumb01_L': {'node': 'LeftHandThumb1', 'constraint': 'orient'}},
              {'thumb02_L': {'node': 'LeftHandThumb2', 'constraint': 'orient'}},
              {'thumb03_L': {'node': 'LeftHandThumb3', 'constraint': 'orient'}},
              {'indexMetacarpal_L': {'node': '', 'constraint': 'orient'}},
              {'index01_L': {'node': 'LeftHandIndex1', 'constraint': 'orient'}},
              {'index02_L': {'node': 'LeftHandIndex2', 'constraint': 'orient'}},
              {'index03_L': {'node': 'LeftHandIndex3', 'constraint': 'orient'}},
              {'middleMetacarpal_L': {'node': '', 'constraint': 'orient'}},
              {'middle01_L': {'node': 'LeftHandMiddle1', 'constraint': 'orient'}},
              {'middle02_L': {'node': 'LeftHandMiddle2', 'constraint': 'orient'}},
              {'middle03_L': {'node': 'LeftHandMiddle3', 'constraint': 'orient'}},
              {'ringMetacarpal_L': {'node': '', 'constraint': 'orient'}},
              {'ring01_L': {'node': 'LeftHandRing1', 'constraint': 'orient'}},
              {'ring02_L': {'node': 'LeftHandRing2', 'constraint': 'orient'}},
              {'ring03_L': {'node': 'LeftHandRing3', 'constraint': 'orient'}},
              {'pinkyMetacarpal_L': {'node': '', 'constraint': 'orient'}},
              {'pinky01_L': {'node': 'LeftHandPinky1', 'constraint': 'orient'}},
              {'pinky02_L': {'node': 'LeftHandPinky2', 'constraint': 'orient'}},
              {'pinky03_L': {'node': 'LeftHandPinky3', 'constraint': 'orient'}}
              ]

ACCU_RIG_OPTIONS = {"autoRightSide": True,
                    "leftIdentifier": "_L",
                    "rightIdentifier": "_R",
                    "maintainOffset": True,
                    "leftRightUnderscore": False,
                    "leftRightPrefix": False,
                    "leftRightSuffix": False}

ACCU_RIG_JOINTS = [{'root': {'node': 'CC_Base_Hip', 'constraint': 'parent'}},
                   {'shoulder_L': {'node': 'CC_Base_L_Upperarm', 'constraint': 'orient'}},
                   {'elbow_L': {'node': 'CC_Base_L_Forearm', 'constraint': 'orient'}},
                   {'wrist_L': {'node': 'CC_Base_L_Hand', 'constraint': 'orient'}},
                   {'thigh_L': {'node': 'CC_Base_L_Thigh', 'constraint': 'orient'}},
                   {'knee_L': {'node': 'CC_Base_L_Calf', 'constraint': 'orient'}},
                   {'ankle_L': {'node': 'CC_Base_L_Foot', 'constraint': 'orient'}},
                   {'ball_L': {'node': 'CC_Base_L_ToeBase', 'constraint': 'orient'}},
                   {'clavicle_L': {'node': 'CC_Base_L_Clavicle', 'constraint': 'orient'}},
                   {'neck01': {'node': 'CC_Base_NeckTwist01', 'constraint': 'orient'}},
                   {'neck02': {'node': 'CC_Base_NeckTwist02', 'constraint': 'orient'}},
                   {'head': {'node': 'CC_Base_Head', 'constraint': 'orient'}},
                   {'spine00': {'node': 'CC_Base_Waist', 'constraint': 'orient'}},
                   {'spine01': {'node': 'CC_Base_Spine01', 'constraint': 'orient'}},
                   {'spine02': {'node': 'CC_Base_Spine02', 'constraint': 'orient'}},
                   {'spine03': {'node': '', 'constraint': 'orient'}},
                   {'spine04': {'node': '', 'constraint': 'orient'}},
                   {'spine05': {'node': '', 'constraint': 'orient'}},
                   {'spine06': {'node': '', 'constraint': 'orient'}},
                   {'spine07': {'node': '', 'constraint': 'orient'}},
                   {'spine08': {'node': '', 'constraint': 'orient'}},
                   {'spine09': {'node': '', 'constraint': 'orient'}},
                   {'spine10': {'node': '', 'constraint': 'orient'}},
                   {'thumb01_L': {'node': 'CC_Base_L_Thumb1', 'constraint': 'orient'}},
                   {'thumb02_L': {'node': 'CC_Base_L_Thumb2', 'constraint': 'orient'}},
                   {'thumb03_L': {'node': 'CC_Base_L_Thumb3', 'constraint': 'orient'}},
                   {'indexMetacarpal_L': {'node': '', 'constraint': 'orient'}},
                   {'index01_L': {'node': 'CC_Base_L_Index1', 'constraint': 'orient'}},
                   {'index02_L': {'node': 'CC_Base_L_Index2', 'constraint': 'orient'}},
                   {'index03_L': {'node': 'CC_Base_L_Index3', 'constraint': 'orient'}},
                   {'middleMetacarpal_L': {'node': '', 'constraint': 'orient'}},
                   {'middle01_L': {'node': 'CC_Base_L_Mid1', 'constraint': 'orient'}},
                   {'middle02_L': {'node': 'CC_Base_L_Mid2', 'constraint': 'orient'}},
                   {'middle03_L': {'node': 'CC_Base_L_Mid3', 'constraint': 'orient'}},
                   {'ringMetacarpal_L': {'node': '', 'constraint': 'orient'}},
                   {'ring01_L': {'node': 'CC_Base_L_Ring1', 'constraint': 'orient'}},
                   {'ring02_L': {'node': 'CC_Base_L_Ring2', 'constraint': 'orient'}},
                   {'ring03_L': {'node': 'CC_Base_L_Ring3', 'constraint': 'orient'}},
                   {'pinkyMetacarpal_L': {'node': '', 'constraint': 'orient'}},
                   {'pinky01_L': {'node': 'CC_Base_L_Pinky1', 'constraint': 'orient'}},
                   {'pinky02_L': {'node': 'CC_Base_L_Pinky2', 'constraint': 'orient'}},
                   {'pinky03_L': {'node': 'CC_Base_L_Pinky3', 'constraint': 'orient'}}
                   ]

UE5_JOINTS_OPTIONS = {"autoRightSide": True,
                      "leftIdentifier": "_l",
                      "rightIdentifier": "_r",
                      "maintainOffset": True,
                      "leftRightUnderscore": False,
                      "leftRightPrefix": False,
                      "leftRightSuffix": False}

UE5_JOINTS = [{'root': {'node': 'pelvis', 'constraint': 'parent'}},
              {'shoulder_L': {'node': 'upperarm_l', 'constraint': 'orient'}},
              {'elbow_L': {'node': 'lowerarm_l', 'constraint': 'orient'}},
              {'wrist_L': {'node': 'hand_l', 'constraint': 'orient'}},
              {'thigh_L': {'node': 'thigh_l', 'constraint': 'orient'}},
              {'knee_L': {'node': 'calf_l', 'constraint': 'orient'}},
              {'ankle_L': {'node': 'foot_l', 'constraint': 'orient'}},
              {'ball_L': {'node': 'ball_l', 'constraint': 'orient'}},
              {'clavicle_L': {'node': 'clavicle_l', 'constraint': 'orient'}},
              {'neck01': {'node': 'neck_01', 'constraint': 'orient'}},
              {'neck02': {'node': 'neck_02', 'constraint': 'orient'}},
              {'head': {'node': 'head', 'constraint': 'orient'}},
              {'spine00': {'node': 'spine_03', 'constraint': 'orient'}},
              {'spine01': {'node': 'spine_04', 'constraint': 'orient'}},
              {'spine02': {'node': 'spine_05', 'constraint': 'orient'}},
              {'spine03': {'node': '', 'constraint': 'orient'}},
              {'spine04': {'node': '', 'constraint': 'orient'}},
              {'spine05': {'node': '', 'constraint': 'orient'}},
              {'spine06': {'node': '', 'constraint': 'orient'}},
              {'spine07': {'node': '', 'constraint': 'orient'}},
              {'spine08': {'node': '', 'constraint': 'orient'}},
              {'spine09': {'node': '', 'constraint': 'orient'}},
              {'spine10': {'node': '', 'constraint': 'orient'}},
              {'thumb01_L': {'node': 'thumb_01_l', 'constraint': 'orient'}},
              {'thumb02_L': {'node': 'thumb_02_l', 'constraint': 'orient'}},
              {'thumb03_L': {'node': 'thumb_03_l', 'constraint': 'orient'}},
              {'indexMetacarpal_L': {'node': 'index_metacarpal_l', 'constraint': 'orient'}},
              {'index01_L': {'node': 'index_01_l', 'constraint': 'orient'}},
              {'index02_L': {'node': 'index_02_l', 'constraint': 'orient'}},
              {'index03_L': {'node': 'index_03_l', 'constraint': 'orient'}},
              {'middleMetacarpal_L': {'node': 'middle_metacarpal_l', 'constraint': 'orient'}},
              {'middle01_L': {'node': 'middle_01_l', 'constraint': 'orient'}},
              {'middle02_L': {'node': 'middle_02_l', 'constraint': 'orient'}},
              {'middle03_L': {'node': 'middle_03_l', 'constraint': 'orient'}},
              {'ringMetacarpal_L': {'node': 'ring_metacarpal_l', 'constraint': 'orient'}},
              {'ring01_L': {'node': 'ring_01_l', 'constraint': 'orient'}},
              {'ring02_L': {'node': 'ring_02_l', 'constraint': 'orient'}},
              {'ring03_L': {'node': 'ring_03_l', 'constraint': 'orient'}},
              {'pinkyMetacarpal_L': {'node': 'pinky_metacarpal_l', 'constraint': 'orient'}},
              {'pinky01_L': {'node': 'pinky_01_l', 'constraint': 'orient'}},
              {'pinky02_L': {'node': 'pinky_02_l', 'constraint': 'orient'}},
              {'pinky03_L': {'node': 'pinky_03_l', 'constraint': 'orient'}}
              ]

HIVE_BIPED_STRD_JOINTS_OPTIONS = {"autoRightSide": True,
                                  "leftIdentifier": "_L",
                                  "rightIdentifier": "_R",
                                  "maintainOffset": True,
                                  "leftRightUnderscore": False,
                                  "leftRightPrefix": False,
                                  "leftRightSuffix": False}

HIVE_BIPED_STRD_JOINTS = [{'root': {'node': 'spine_M_00_jnt', 'constraint': 'parent'}},
                          {'shoulder_L': {'node': 'arm_L_shldr_jnt', 'constraint': 'orient'}},
                          {'elbow_L': {'node': 'arm_L_elbow_jnt', 'constraint': 'orient'}},
                          {'wrist_L': {'node': 'arm_L_wrist_jnt', 'constraint': 'orient'}},
                          {'thigh_L': {'node': 'leg_L_upr_jnt', 'constraint': 'orient'}},
                          {'knee_L': {'node': 'leg_L_knee_jnt', 'constraint': 'orient'}},
                          {'ankle_L': {'node': 'leg_L_foot_jnt', 'constraint': 'orient'}},
                          {'ball_L': {'node': 'leg_L_ball_jnt', 'constraint': 'orient'}},
                          {'clavicle_L': {'node': 'clavicle_L_00_jnt', 'constraint': 'orient'}},
                          {'neck01': {'node': 'head_M_neck_jnt', 'constraint': 'orient'}},
                          {'neck02': {'node': '', 'constraint': 'orient'}},
                          {'head': {'node': 'head_M_head_jnt', 'constraint': 'orient'}},
                          {'spine00': {'node': 'spine_M_01_jnt', 'constraint': 'orient'}},
                          {'spine01': {'node': 'spine_M_02_jnt', 'constraint': 'orient'}},
                          {'spine02': {'node': 'spine_M_03_jnt', 'constraint': 'orient'}},
                          {'spine03': {'node': 'spine_M_04_jnt', 'constraint': 'orient'}},
                          {'spine04': {'node': 'spine_M_05_jnt', 'constraint': 'orient'}},
                          {'spine05': {'node': 'spine_M_06_jnt', 'constraint': 'orient'}},
                          {'spine06': {'node': 'spine_M_07_jnt', 'constraint': 'orient'}},
                          {'spine07': {'node': 'spine_M_08_jnt', 'constraint': 'orient'}},
                          {'spine08': {'node': 'spine_M_09_jnt', 'constraint': 'orient'}},
                          {'spine09': {'node': 'spine_M_10_jnt', 'constraint': 'orient'}},
                          {'spine10': {'node': 'spine_M_11_jnt', 'constraint': 'orient'}},
                          {'thumb01': {'node': 'finger_thumb_L_00_jnt', 'constraint': 'orient'}},
                          {'thumb02': {'node': 'finger_thumb_L_01_jnt', 'constraint': 'orient'}},
                          {'thumb03': {'node': 'finger_thumb_L_02_jnt', 'constraint': 'orient'}},
                          {'indexMetacarpal_L': {'node': 'finger_pointer_L_00_jnt', 'constraint': 'orient'}},
                          {'index01_L': {'node': 'finger_pointer_L_01_jnt', 'constraint': 'orient'}},
                          {'index02_L': {'node': 'finger_pointer_L_02_jnt', 'constraint': 'orient'}},
                          {'index03_L': {'node': 'finger_pointer_L_03_jnt', 'constraint': 'orient'}},
                          {'middleMetacarpal_L': {'node': 'finger_middle_L_00_jnt', 'constraint': 'orient'}},
                          {'middle01_L': {'node': 'finger_middle_L_01_jnt', 'constraint': 'orient'}},
                          {'middle02_L': {'node': 'finger_middle_L_02_jnt', 'constraint': 'orient'}},
                          {'middle03_L': {'node': 'finger_middle_L_03_jnt', 'constraint': 'orient'}},
                          {'ringMetacarpal_L': {'node': 'finger_ring_L_00_jnt', 'constraint': 'orient'}},
                          {'ring01_L': {'node': 'finger_ring_L_01_jnt', 'constraint': 'orient'}},
                          {'ring02_L': {'node': 'finger_ring_L_02_jnt', 'constraint': 'orient'}},
                          {'ring03_L': {'node': 'finger_ring_L_03_jnt', 'constraint': 'orient'}},
                          {'pinkyMetacarpal_L': {'node': 'finger_pinky_L_00_jnt', 'constraint': 'orient'}},
                          {'pinky01_L': {'node': 'finger_pinky_L_01_jnt', 'constraint': 'orient'}},
                          {'pinky02_L': {'node': 'finger_pinky_L_02_jnt', 'constraint': 'orient'}},
                          {'pinky03_L': {'node': 'finger_pinky_L_03_jnt', 'constraint': 'orient'}}
                          ]

HIVE_BIPED_LIGHT_JOINTS = list(HIVE_BIPED_STRD_JOINTS)  # Use STRD joints just change spine and root
HIVE_BIPED_LIGHT_JOINTS[0] = {'root': {'node': 'spine_M_cog_jnt', 'constraint': 'parent'}}
HIVE_BIPED_LIGHT_JOINTS[12] = {'spine00': {'node': 'spine_M_01_jnt', 'constraint': 'orient'}}
HIVE_BIPED_LIGHT_JOINTS[13] = {'spine01': {'node': '', 'constraint': 'orient'}}
HIVE_BIPED_LIGHT_JOINTS[14] = {'spine02': {'node': 'spine_M_02_jnt', 'constraint': 'orient'}}

HIVE_BIPED_UE5_JOINTS = list(UE5_JOINTS)  # use UE5 joints just change root
HIVE_BIPED_UE5_JOINTS[0] = {'root': {'node': 'hipsSwing', 'constraint': 'parent'}}
HIVE_BIPED_UE5_JOINTS_OPTIONS = dict(UE5_JOINTS_OPTIONS)

ALL_MAPPINGS = [{"Hive Biped Controls": {"nodes": HIVE_BIPED_STRD_CTRLS, "options": HIVE_BIPED_STRD_OPTIONS}},
                {"Hive Biped Light Ctrls": {"nodes": HIVE_BIPED_LIGHT_CTRLS, "options": HIVE_BIPED_STRD_OPTIONS}},
                {"Hive Biped UE Ctrls": {"nodes": HIVE_BIPED_UE_CTRLS, "options": HIVE_BIPED_UE_OPTIONS}},
                {"Skele Blder Biped Ctrls": {"nodes": SKELE_BUILDER_CTRLS, "options": SKELE_BUILDER_OPTIONS}},
                {"--- Joints ---": {}},
                {"HIVE Biped Strd Jnts": {"nodes": HIVE_BIPED_STRD_JOINTS, "options": HIVE_BIPED_STRD_JOINTS_OPTIONS}},
                {"HIVE Biped Light Jnts": {"nodes": HIVE_BIPED_LIGHT_JOINTS, "options": HIVE_BIPED_STRD_JOINTS_OPTIONS}},
                {"Hive BIPED UE Jnts": {"nodes": HIVE_BIPED_UE5_JOINTS, "options": HIVE_BIPED_UE5_JOINTS_OPTIONS}},
                {"HIK Jnts": {"nodes": HIK_JOINTS, "options": HIK_OPTIONS}},
                {"Quick Rig Jnts": {"nodes": HIK_JOINTS, "options": HIK_OPTIONS}},
                {"Mixamo Jnts": {"nodes": HIK_JOINTS, "options": HIK_OPTIONS}},
                {"Rokoko Jnts": {"nodes": HIK_JOINTS, "options": HIK_OPTIONS}},
                {"UE5 Jnts": {"nodes": UE5_JOINTS, "options": UE5_JOINTS_OPTIONS}},
                {"AccuRig Jnts": {"nodes": ACCU_RIG_JOINTS, "options": ACCU_RIG_OPTIONS}},
                {"Skele Bldr Jnts": {"nodes": SKELE_BUILDER_JOINTS, "options": SKELE_BUILDER_OPTIONS}}]

ALL_MAPPINGS_TODO = [{"Hive Biped Controls": {"nodes": HIVE_BIPED_STRD_CTRLS, "options": HIVE_BIPED_STRD_OPTIONS}},
                     {"Hive Biped Light Ctrls": {"nodes": HIVE_BIPED_LIGHT_CTRLS, "options": HIVE_BIPED_STRD_OPTIONS}},
                     {"Hive Biped UE Ctrls": {"nodes": HIVE_BIPED_UE_CTRLS, "options": HIVE_BIPED_UE_OPTIONS}},
                     {"Skele Blder Biped Ctrls": {"nodes": SKELE_BUILDER_CTRLS, "options": SKELE_BUILDER_OPTIONS}},
                     {"MGear Ctrls": {"nodes": ACCU_RIG_JOINTS, "options": ACCU_RIG_OPTIONS}},
                     {"Advanced Skele Ctrls": {"nodes": ACCU_RIG_JOINTS, "options": ACCU_RIG_OPTIONS}},
                     {"--- Joints ---": {}},
                     {"HIVE Biped Strd Jnts": {"nodes": HIVE_BIPED_STRD_JOINTS, "options": HIVE_BIPED_STRD_JOINTS_OPTIONS}},
                     {"HIVE Biped Light Jnts": {"nodes": HIVE_BIPED_LIGHT_JOINTS, "options": HIVE_BIPED_STRD_JOINTS_OPTIONS}},
                     {"Hive BIPED UE Jnts": {"nodes": HIVE_BIPED_UE5_JOINTS, "options": HIVE_BIPED_UE5_JOINTS_OPTIONS}},
                     {"HIK Jnts": {"nodes": HIK_JOINTS, "options": HIK_OPTIONS}},
                     {"Quick Rig Jnts": {"nodes": HIK_JOINTS, "options": HIK_OPTIONS}},
                     {"Mixamo Jnts": {"nodes": HIK_JOINTS, "options": HIK_OPTIONS}},
                     {"Rokoko Jnts": {"nodes": HIK_JOINTS, "options": HIK_OPTIONS}},
                     {"UE5 Jnts": {"nodes": UE5_JOINTS, "options": UE5_JOINTS_OPTIONS}},
                     {"AccuRig Jnts": {"nodes": ACCU_RIG_JOINTS, "options": ACCU_RIG_OPTIONS}},
                     {"Daz CC Jnts": {"nodes": ACCU_RIG_JOINTS, "options": ACCU_RIG_OPTIONS}},
                     {"Skele Bldr Jnts": {"nodes": SKELE_BUILDER_JOINTS, "options": SKELE_BUILDER_OPTIONS}},
                     {"MGear Jnts": {"nodes": ACCU_RIG_JOINTS, "options": ACCU_RIG_OPTIONS}},
                     {"Advanced Skele Jnts": {"nodes": ACCU_RIG_JOINTS, "options": ACCU_RIG_OPTIONS}},
                     {"--- User Presets ---": {}}]
